name: no_std

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install wasm32-unknown-unknown
        run: rustup target add wasm32-unknown-unknown
      - name: Check without default features
        run: cargo check -p quither --no-default-features
      - name: Check without default features for wasm32-unknown-unknown
        run: cargo check -p quither --no-default-features --target wasm32-unknown-unknown
      - name: Doc-test without default features
        run: cargo test -p quither --doc --no-default-features
      - name: Test without default features
        run: cargo test -p quither --no-default-features
